In [18]:
import numpy as np

In [19]:
# conjunto básico de dados
data = np.array([[True,True], [True,False], [False,True], [False,False]])

# definição de viés (bias)
bias = -2


# resultado de 'and'  
_and = [x[0] and x[1]  for x in data]

# resultado de 'or'
_or = [x[0] or x[1]  for x in data]

_and, type(_or)

([True, False, False, False], list)

In [20]:
def my_perception(input_:np.array, bias_):
    pred = input_.sum() + bias_
    return pred <= 0

# testando 'and'
for row in zip(data, _or): 
    print(row, my_perception(row[0], bias))

(array([ True,  True]), True) True
(array([ True, False]), True) True
(array([False,  True]), True) True
(array([False, False]), False) True


In [22]:
# som(atributos) + soma(calsses) /2 

atributos = 10
classes = 2
quantidade_neuronios = (atributos+classes)/2

epoc é quantidade de rodadas para ajustar os pessos usando backpropagation

6.0