In [2]:
import numpy as np

In [16]:
# conjunto básico de dados
data = np.array([[True,True], [True,False], [False,True], [False,False]])

# definição de viés (bias)
bias = -1


# resultado de 'and'  
_and = [x[0] and x[1]  for x in data]

# resultado de 'or'
_or = [x[0] or x[1]  for x in data]

_and, type(_or)

([True, False, False, False], list)

In [20]:
def my_perception(input_:np.array, bias_):
    pred = bool(input_.sum() + bias_)
    return pred

# testando 'and'
for row in zip(data, _and): 
    print(row, my_perception(row[0], bias))

(array([ True,  True]), True) True
(array([ True, False]), False) False
(array([False,  True]), False) False
(array([False, False]), False) True
